version: '3.1'
services:
  mysql:
    image: mysql:5.6@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3309:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central

  localstack:
    image: localstack/localstack@sha256:ddceaf8467b309ed14a6478772bc84ce7195f2ce77b3a182958dfd3b7fa85a94
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=kinesis,firehose,sqs
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:1817bb941c9a30fe2a6d75ff8675a8f6def408efe3d3ff43dbb006e2b534fa14
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4005:4005'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
      - .env
    environment:
      - NODE_ENV=local
    entrypoint: ./.docker/scripts/local-start.sh
    depends_on:
      - mysql
      - localstack
      - snowplow

  snowplow:
    image: pocket/snowplow-micro:prod
    platform: linux/amd64
    ports:
      - '9090:9090'
