version: '3.1'
services:
  mysql:
    image: mysql:5.6
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3309:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central

  localstack:
    image: localstack/localstack@sha256:e3590b6fa651150cb2cde7dfe3129125148e9301b1fa9cba74a71bf234e195da
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=kinesis,firehose,sqs
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:68e34cfcd8276ad531b12b3454af5c24cd028752dfccacce4e19efef6f7cdbe0
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4005:4005'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
      - .env
    environment:
      - NODE_ENV=local
    entrypoint: ./.docker/scripts/local-start.sh
    depends_on:
      - mysql
      - localstack
      - snowplow

  snowplow:
    image: pocket/snowplow-micro:prod
    platform: linux/amd64
    ports:
      - '9090:9090'
