version: '3.1'
services:
  mysql:
    image: mysql:5.6@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3309:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central

  localstack:
    image: localstack/localstack:1.3@sha256:74b94340e37c820cfd523333ee8ce8abf07fceced8c201c7db76eb1cba0b9099
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
    volumes:
      - /etc/localstack/init/ready.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=kinesis,firehose,sqs,events
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  otlpcollector:
    image: amazon/aws-otel-collector@sha256:1addb52aaf4880455aaabcc934924d735212d95e81f5a5fa44ee6a61fa03b8f1
    command: --config=/etc/ecs/ecs-default-config.yaml --set=service.telemetry.logs.level=debug
    env_file:
      - .docker/local.env
    ports:
      - '4137:4137'
      - '4138:4138'

  app:
    image: node:16@sha256:550f484fc5f314b575f5e397c9e2c71d7f218e59729fcda9ffa7ea1fc825dce7
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4005:4005'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
      - .env
    environment:
      - NODE_ENV=local
      - TZ=US/Central
    entrypoint: ./.docker/scripts/local-start.sh
    depends_on:
      - mysql
      - localstack
      - snowplow
      - otlpcollector

  snowplow:
    image: pocket/snowplow-micro:prod
    platform: linux/amd64
    ports:
      - '9090:9090'
