version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.docker/local.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      TZ: 'US/Central'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    platform: linux/amd64
    command:
      - mysqld
      - --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - '3309:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated

  localstack:
    image: localstack/localstack:3.0.1
    env_file:
      - .docker/local.env
    environment:
      LOCALSTACK_HOST: localstack
      SERVICES: 'kinesis,firehose,sqs,events'
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:4566/_localstack/health
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/etc/localstack/init/ready.d

  otlpcollector:
    image: amazon/aws-otel-collector
    command: --config=/etc/ecs/ecs-default-config.yaml --set=service.telemetry.logs.level=error
    env_file:
      - .docker/local.env
    ports:
      - '4137:4137'
      - '4138:4138'

  snowplow:
    image: pocket/snowplow-micro:prod
    ports:
      - '9090:9090'

  app:
    image: node:20
    working_dir: /app
    ports:
      - '4005:4005'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
      - .env
    environment:
      - NODE_ENV=local
      - TZ=US/Central
    entrypoint: ./.docker/scripts/local-start.sh
    depends_on:
      localstack:
        condition: service_healthy
      mysql:
        condition: service_healthy
      otlpcollector:
        condition: service_started
      snowplow:
        condition: service_started
